anchor_version = "0.27.0"
solana_version = "1.17.17"

[features]
seeds = false
skip-lint = false

[programs.localnet]
usdfg_smart_contract = "HZo7FxeeknDvZtYcpqjgehKjNXRumduGRfLGJkDZLRgL"

[programs.devnet]
usdfg_smart_contract = "HZo7FxeeknDvZtYcpqjgehKjNXRumduGRfLGJkDZLRgL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/husseinali/.config/solana/id.json"

[workspace]
members = [
    "programs/usdfg_smart_contract",
]
types = "target/types"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 